Draft: CI: Check that the udev rules work
Test doesn't work yet.

diff --git a/test/testscript b/test/testscript
--- a/test/testscript
+++ b/test/testscript
@@ -11,11 +11,17 @@ cat >>/usr/bin/combustion-validate <<'EOF'
 #!/bin/bash
 set -euxo pipefail
 exec &>/dev/ttyS0
+echo root:linux | chpasswd
 trap '[ $? -eq 0 ] || poweroff -f' EXIT
+journalctl | cat
+if journalctl -b | grep "Timed out waiting for device /dev/combustion/config"; then
+    echo "FAILED: timeout"
+    exit 1
+fi
 mount -t 9p -o trans=virtio tmpdir /mnt
 touch /mnt/done
 umount /mnt
-poweroff
+poweroff -f
 EOF
 chmod a+x /usr/bin/combustion-validate
 
@@ -25,4 +31,4 @@ ExecStart=/usr/bin/combustion-validate
 [Install]
 RequiredBy=default.target
 EOF
-systemctl enable combustion-validate.service
+#systemctl enable combustion-validate.service
