Let selinux-microos-relabel decide whether a relabel is necessary (bsc#1202437)
Don't look at the autorelabel flags ourselves, just run the hook if it's
there and have a safeguard in the case that it's missing but we know it needs
to be there.

diff --git a/combustion b/combustion
--- a/combustion
+++ b/combustion
@@ -129,8 +129,11 @@ fi
 awk '$4 ~ /x-initrd.mount/ { system("findmnt /sysroot" $2 " >/dev/null || mount -t " $3 " -o " $4 " " $1 " /sysroot" $2) }' /sysroot/etc/fstab
 
 # Make sure the old snapshot is relabeled too, otherwise syncing its /etc fails.
-if [ -e /sysroot/etc/selinux/.autorelabel ]; then
+if [ -e /lib/dracut/hooks/pre-pivot/50-selinux-microos-relabel.sh ]; then
 	NEWROOT=/sysroot bash -c '. /lib/dracut-lib.sh; . /lib/dracut/hooks/pre-pivot/50-selinux-microos-relabel.sh'
+elif [ -e /sysroot/.autorelabel ] || [ -e /sysroot/etc/selinux/.autorelabel ]; then
+	echo "Relabel (probably) needed, but selinux-microos-relabel not found."
+	exit 1
 fi
 
 # Prepare chroot
