Populate /dev/shm/combustion/ in the --prepare stage
Instead of keeping config_mount around until the full combustion run, copy the
config into $exchangedir during the prepare stage. This makes the separation
between those stages clearer and simpler.

Also don't delete exchangedir on prepare failure, keep it around for debugging.

diff --git a/combustion b/combustion
--- a/combustion
+++ b/combustion
@@ -4,52 +4,72 @@
 set -euo pipefail
 
 config_mount="/run/combustion/mount"
+# Use /dev/shm for data exchange
+exchangedir="/dev/shm/combustion/"
+config_dir="${exchangedir}/config"
 
 if [ "${1-}" = "--prepare" ]; then
-	# Mount config drive
-	mkdir -p "${config_mount}"
-
-	config_drive_found=0
+	rm -rf "${exchangedir}"
+	mkdir "${exchangedir}"
 
 	# Try fw_cfg first
 	if [ -e "/sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion" ]; then
-		mkdir -p "${config_mount}/combustion"
+		mkdir -p "${config_dir}"
 		if ! cp /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion/script/raw \
-		        "${config_mount}/combustion/script"; then
+		        "${config_dir}/script"; then
 			echo "Failed to copy script from fw_cfg!"
 			exit 1
 		fi
 		# TODO: Support other files, e.g. with a tarball or fs image?
-
-		config_drive_found=1
 	fi
 
 	# Try disks next - both lower and upper case
 	for label in combustion COMBUSTION ignition IGNITION; do
-		[ "${config_drive_found}" = "1" ] && break
+		[ -d "${config_dir}" ] && break
 		[ -e "/dev/disk/by-label/${label}" ] || continue
 
+		mkdir -p "${config_mount}"
 		if ! mount -o ro /dev/disk/by-label/${label} "${config_mount}"; then
 			echo "Failed to mount config drive!"
+			rmdir "${config_mount}"
 			exit 1
 		fi
 
-                config_drive_found=1
+		if [ -d "${config_mount}/combustion" ]; then
+			if ! cp -R "${config_mount}/combustion" "${config_dir}"; then
+				echo "Failed to copy config!"
+				rm -rf "${config_dir}"
+				umount "${config_mount}"
+				rmdir "${config_mount}"
+				exit 1
+			fi
+		else
+			echo "No config found on drive."
+		fi
+
+		umount "${config_mount}"
+		rmdir "${config_mount}"
 	done
 
-	if [ "${config_drive_found}" = "0" ]; then
-		echo "No config drive found"
+	if ! [ -d "${config_dir}" ]; then
+		echo "No config source found"
 		exit 0
 	fi
 
+	if ! [ -e "${config_dir}/script" ]; then
+		echo "No config script found!"
+		exit 1
+	fi
+
+	chmod a+x "${config_dir}/script"
+
 	# Check for the magic flag "# combustion: network" in the script
-	if [ -e "${config_mount}/combustion/script" ] \
-	   && grep -qE '^# combustion:(.*)\<network\>' "${config_mount}/combustion/script"; then
+	if grep -qE '^# combustion:(.*)\<network\>' "${config_dir}/script"; then
 		sh -s <<EOF
 			. /lib/dracut-lib.sh
 			# Set rd.neednet if not already done and reevaluate it (module-specific)
 			getargbool 0 'rd.neednet' && exit 0
-			echo rd.neednet=1  > /etc/cmdline.d/40-combustion-neednet.conf
+			echo rd.neednet=1 > /etc/cmdline.d/40-combustion-neednet.conf
 			if [ -e /lib/dracut/hooks/pre-udev/60-net-genrules.sh ]; then
 				# Wicked
 				. /lib/dracut/hooks/pre-udev/60-net-genrules.sh
@@ -66,18 +86,9 @@ EOF
 	exit 0
 fi
 
-# Use /dev/shm for data exchange
-exchangedir="/dev/shm/combustion/"
 delete_resolv_conf=0
 
 cleanup() {
-	if findmnt "${config_mount}" >/dev/null; then
-		umount "${config_mount}" || true
-		rmdir "${config_mount}" || true
-	else
-		rm -rf "${config_mount}" || true
-	fi
-
 	rm -rf "${exchangedir}" || true
 
 	if [ "${delete_resolv_conf}" -eq 1 ]; then
@@ -102,10 +113,7 @@ cleanup() {
 # This is needed as ignition-mount.service's ExecStop is also disabled unconditionally.
 trap cleanup EXIT
 
-if ! [ -d "${config_mount}/combustion" ]; then
-	echo "No config found - doing nothing."
-	exit 0
-fi
+[ -d "${config_dir}" ] || exit 0
 
 # Make sure /sysroot is mounted
 systemctl start sysroot.mount
@@ -113,16 +121,6 @@ systemctl start sysroot.mount
 # Same for /sysroot/usr if it exists (e.g. through mount.usr)
 if systemctl cat sysroot-usr.mount &>/dev/null; then
 	systemctl start sysroot-usr.mount
-fi
-
-# Copy config
-mkdir "${exchangedir}"
-config_dir="${exchangedir}/config"
-cp -R "${config_mount}/combustion" "${config_dir}"
-
-if ! [ -e "${config_dir}/script" ]; then
-	echo "No config script found."
-	exit 1
 fi
 
 # Have to take care of x-initrd.mount first and from the outside
@@ -165,7 +163,6 @@ if [ -x /sysroot/usr/sbin/transactional-update ]; then
 	# also ignores the shell's exit code, so DIY.
 	if ! chroot /sysroot transactional-update shell <<EOF; then
 		cd "${config_dir}"
-		chmod a+x script
 		./script
 		echo \$? > "${exchangedir}/retval"
 		# Snapshot got touched while the policy isn't active, needs relabeling again.
