Use dracut $hookdir instead of hardcoding

diff --git a/combustion b/combustion
--- a/combustion
+++ b/combustion
@@ -95,20 +95,20 @@ if [ "${1-}" = "--prepare" ]; then
 
 	# Check for the magic flag "# combustion: network" in the script
 	if grep -qE '^# combustion:(.*)\<network\>' "${config_dir}/script"; then
-		sh -s <<EOF
+		sh -s <<'EOF'
 			. /lib/dracut-lib.sh
 			# Set rd.neednet if not already done and reevaluate it (module-specific)
 			getargbool 0 'rd.neednet' && exit 0
 			echo rd.neednet=1 > /etc/cmdline.d/40-combustion-neednet.conf
-			if [ -e /lib/dracut/hooks/pre-udev/60-net-genrules.sh ]; then
+			if [ -e "${hookdir}/pre-udev/60-net-genrules.sh" ]; then
 				# Wicked
-				. /lib/dracut/hooks/pre-udev/60-net-genrules.sh
+				. "${hookdir}/pre-udev/60-net-genrules.sh"
 				# Re-trigger generation of network rules and apply them
 				udevadm control --reload
 				udevadm trigger --subsystem-match net --action add
 			else
 				# NetworkManager
-				. /lib/dracut/hooks/cmdline/99-nm-config.sh
+				. "${hookdir}/cmdline/99-nm-config.sh"
 			fi
 EOF
 	fi
@@ -185,12 +185,17 @@ mount --make-private /sysroot
 awk '$1 !~ /^#/ && $4 ~ /(\<|,)x-initrd\.mount(\>|,)/ { if(system("findmnt /sysroot/" $2 " >/dev/null || mount --target-prefix /sysroot --fstab /sysroot/etc/fstab " $2) != 0) exit 1; }' /sysroot/etc/fstab
 
 # Make sure the old snapshot is relabeled too, otherwise syncing its /etc fails.
-if [ -e /lib/dracut/hooks/pre-pivot/50-selinux-microos-relabel.sh ]; then
-	NEWROOT=/sysroot bash -c '. /lib/dracut-lib.sh; . /lib/dracut/hooks/pre-pivot/50-selinux-microos-relabel.sh'
-elif [ -e /sysroot/.autorelabel ] || [ -e /sysroot/etc/selinux/.autorelabel ]; then
-	echo "Relabel (probably) needed, but selinux-microos-relabel not found."
-	exit 1
-fi
+(
+	set +eu
+	. /lib/dracut-lib.sh
+	set -eu
+	if [ -e "${hookdir}/pre-pivot/50-selinux-microos-relabel.sh" ]; then
+		NEWROOT=/sysroot bash -c '. /lib/dracut-lib.sh; . "${hookdir}/pre-pivot/50-selinux-microos-relabel.sh"'
+	elif [ -e /sysroot/.autorelabel ] || [ -e /sysroot/etc/selinux/.autorelabel ]; then
+		echo "ERROR: Relabel (probably) needed, but selinux-microos-relabel not found."
+		exit 1
+	fi
+)
 
 # Prepare chroot
 for i in proc sys dev; do
