Only attempt firstboot check on devices
Otherwise firstboot-detect attempts to mount the kiwi dump source device.

diff --git a/30firstboot/firstboot-detect b/30firstboot/firstboot-detect
--- a/30firstboot/firstboot-detect
+++ b/30firstboot/firstboot-detect
@@ -1,7 +1,15 @@
 #!/bin/sh
 set -eu
-what=$(systemctl show -P What sysroot.mount)
-opts=$(systemctl show -P Options sysroot.mount)
+what="$(systemctl show -P What sysroot.mount)"
+opts="$(systemctl show -P Options sysroot.mount)"
+
+# Catch cases where sysroot isn't a device,
+# especially kiwi's install:CDLABEL=INSTALL syntax.
+if ! echo "$what" | grep -q ^/; then
+	echo "Unable to detect firstboot on $what" >&2
+	exit 0
+fi
+
 mount -o "$opts" "$what" /sysroot
 
 # Handle x-initrd.mount without initrd-parse-etc.service
