30firstboot: Leave IPL DASD enablement to s390-tools (jsc#PED-8130)
Setting dasd_mod.dasd=ipldev prevents module loading if the IPL device is not
a DASD, so it can only be done conditionally.

diff --git a/30firstboot/firstboot-detect b/30firstboot/firstboot-detect
--- a/30firstboot/firstboot-detect
+++ b/30firstboot/firstboot-detect
@@ -22,7 +22,7 @@ if ! [ -e /sysroot/etc/machine-id ] \
 		# On s390x, attached DASDs need to be enabled first to appear as block devices.
 		# On the first boot this is necessary to probe for configuration sources.
 		echo "Trying to enable all available DASDs"
-		chzdev dasd --offline --existing --enable --active || echo "Couldn't enable all devices, trying to continue anyway." >&2
+		chzdev dasd --offline --existing --enable --active || echo "Couldn't enable all DASD devices, trying to continue anyway." >&2
 	fi
 	# Make initrd.target require firstboot.target
 	systemctl enable --quiet firstboot.target
